[build]
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Redirects for cleaner API paths
[[redirects]]
  from = "/contact"
  to = "/.netlify/functions/contact"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200
